# Configuración para el build de Netlify
[build]
  # Directorio base: Netlify entrará aquí antes de ejecutar cualquier comando.
  base = "client"
  
  # Comando de build: El comando que construye tu app de React.
  command = "npm run build"
  
  # Directorio de publicación: La carpeta que contiene el sitio final, relativa al 'base'.
  publish = "dist"

# Regla de redirección para Single-Page Applications (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200